version = "3.7.17"

runner.dialect = scala3

# --- Layout / indentation ---
maxColumn = 100
align.preset = none
align.multiline = false
align.openParenCallSite = false

indent.main = 2
indent.callSite = 2
indent.defnSite = 2

continuationIndent.callSite = 2
continuationIndent.defnSite = 2

# --- Style ---
optIn.annotationNewlines = true
optIn.breakChainOnFirstMethodDot = true

# --- Literals & collections ---
# spaces.beforeContextualComma = false
spaces.inImportCurlyBraces = true

# --- Rewrites ---
rewrite.rules = [
  RedundantParens,
  RedundantBraces,
  SortImports,
  PreferCurlyFors
]


# --- Comments ---
docstrings.style = Asterisk
docstrings.oneline = fold

# --- Misc ---
includeCurlyBraceInSelectChains = false
danglingParentheses.preset = true
trailingCommas = multiple
